Repository health-connector/quoting_tool, pull requests merged in 2019-11, with the labels that each got.

#63 61500
  clients/html/src/app/app.component.ts
  clients/html/src/app/custom_date_parser_formatter.ts
  clients/html/src/app/employer-details/employer-details.component.html
  clients/html/src/app/employer-details/employer-details.component.ts
  clients/html/src/app/services/plan-provider.service.ts
Labels: Priority: 3-High, Status: Peer Review, Tracker: Feature

#64 63102
  clients/html/src/app/employer-details/employer-details.component.html
Labels: Priority: 4-Normal, Status: Peer Review, Tracker: Use Case

#70 70027
  clients/html/src/app/custom_date_parser_formatter.ts
  clients/html/src/app/employer-details/employer-details.component.html
  clients/html/src/app/employer-details/employer-details.component.ts
Labels: Assignee: Vishal Kalletla, Priority: 4-Normal, Status: In Progress, Tracker: Use Case

#74 70199
  app/models/operations/product_builder.rb
  app/models/products/health_product.rb
  app/serializers/product_serializer.rb
  clients/html/src/app/plan-filter/plan-filter.component.html
Labels: Priority: 4-Normal, Status: Peer Review, Tracker: Feature
